//-Implementation of the algorithm developed by David Hernández Lázaro to write a prime number bigger
// than 2 as a sum of two primes.

#include"PrimeList.hpp"

//-List of ui32-integers pairs.
typedef struct _ui32_pair_list{
    ui32 pair[2];
    _ui32_pair_list *next_pair;
}ui32_pair_list;

//-Looks for a number in a list of type prime. If it's found, return the index in the list. If it's not
// found, it returns -1.
ui32 Find_in_list(ui32 number, pointer_prime list);

//-Given a even number, it returns the a list containing all the numbers generated by the Lazaro method.
// We claim that the last element of this list is a pair of primes, whitch sum is equal to the even
// number passed to the function.
ui32_pair_list* Lazaro_Method(ui32 even_number);

//-Printing a ui32_pair_list list.
void Print_List(ui32_pair_list* list);

//-Realised used memory.
void Deallocate_List(ui32_pair_list* list);