//-Implementation of the algorithm developed by David Hernández Lázaro to write a prime number bigger
// than 2 as a sum of two primes.

#include"PrimeList.hpp"

//-List of ui32-integers pairs.
typedef struct _i32_pair_list{
    int pair[2];
    _i32_pair_list *next_pair;
}i32_pair_list;

//-Given a even number, it returns the a list containing all the numbers generated by the Lazaro method.
// We claim that the last element of this list is a pair of primes, whitch sum is equal to the even
// number passed to the function.
i32_pair_list* Lazaro_Method(ui32 even_number);

//-Given a list it returns the last non-null element. If the list is empty it returns a null pointer.
i32_pair_list* Get_queue(i32_pair_list* list);

//-Printing a i32_pair_list list.
void Print_List(i32_pair_list* list);

//-Realised used memory.
void Deallocate_List(i32_pair_list* list);