#include"Goldbach_Lazaro.hpp"
#include"Error.hpp"
#include<iostream>

int main(int argc, char *argv[]){
    int number;
    std::cout << "Introduce a even number bigger than 2:\n";
    std::cin >> number;

    if (number < 3)
        Error("The number must be bigger than 2.");
    if (number%2 != 0)
        Error("The number must be an even number.");
    
    //-Lazaro-Goldbach list.
    ui32_pair_list* LG_list = Lazaro_Method(number);
    std::cout << "\n The numbers generated by the Lazaro Method are:\n";
    Print_List(LG_list);
    Deallocate_List(LG_list);

    return 0;
}